name: newsscope
description: "NewsScope - A global, bias-aware news aggregator."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.2

  # State management
  provider: ^6.1.2

  # Maps & geolocation
  flutter_map: ^8.2.2

  # Charts & data visualization
  fl_chart: ^1.1.1

  # Icons & UI
  cupertino_icons: ^1.0.8

  # Firebase (latest stable versions)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4   # add this

flutter:
  uses-material-design: true

# Add launcher icon config
flutter_icons:
  android: true
  image_path: "assets/icons/NewsScopeIcon.png"