name: newsscope
description: "NewsScope - A global, bias-aware news aggregator."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.2

  # State management
  provider: ^6.1.2

  # Maps & geolocation
  flutter_map: ^8.2.2

  # Charts & data visualization
  fl_chart: ^1.1.1

  # Icons & UI
  cupertino_icons: ^1.0.8

  # Firebase (latest stable versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
